core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.views.generic import TemplateView
from .views import *

app_name = 'core'

urlpatterns = [
        path('', views.index, name='home'),
        path('search/', views.search, name='search'),
        path('<slug:slug>/', category, name='main-category-detail'),
        path('news/<slug>/', views.news_details, name='news-detail'),
        path('tag/<slug:slug>/', views.tagged, name='tag-detail'),
        path('page/<slug:slug>/', PageDetailView.as_view(), name='page-detail'),


        # path('news/<slug:slug>/', NewsDetailView.as_view(), name='news-detail'),


]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('tinymce/', include('tinymce.urls')),
]

core/models.py
from django.db import models
from autoslug import AutoSlugField
from tinymce.models import HTMLField
from django.contrib.auth.models import User
from django.urls import reverse
from django.template.defaultfilters import slugify
from unidecode import unidecode
from taggit.managers import TaggableManager

# Create your models here.

STATUS_CHOICES = (
    ('D', 'Draft'),
    ('P', 'Published')
)

HOME_NEWS_CHOICES = (
    ('S', 'Slider'),
    ('6', 'Top 6'),
    ('N', 'None'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
        primary_key=True,)
    avatar = models.ImageField(upload_to='avatar/', null=True, blank=True) # user avatar upload
    slug = AutoSlugField(populate_from='username', editable=True, null=True, blank=True)

    def __str__(self):
        return self.user.email


class SiteSettings(models.Model):
    site_title = models.CharField(max_length=200)
    meta_title = models.CharField(max_length=250, blank=True, null=True)
    meta_description = models.TextField(blank=True, null=True)
    meta_keywords = models.CharField(max_length=300, blank=True, null=True,
                                     help_text='Comma Separated Keyword for search engines')
    logo = models.ImageField(upload_to='logo/', blank=True, null=True)
    copyright_text = models.CharField(max_length=120, blank=True, null=True)
    google_analytics_code = models.CharField(max_length=50, blank=True, null=True, help_text='Paste google analytics tracing code: ex. UA-69123876-4')
    alexa_code = models.CharField(max_length=50, blank=True, null=True)
    facebook = models.URLField(blank=True, null=True, help_text='Input your Facebook page url')
    twitter = models.URLField(blank=True, null=True, help_text='Input your Twitter page url')
    youtube = models.URLField(blank=True, null=True, help_text='Input your YouTube page url')
    linkedin = models.URLField(blank=True, null=True, help_text='Input your LinkedIN page url')
    instagram = models.URLField(blank=True, null=True, help_text='Input your Instagram page url')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.site_title

    class Meta:
        verbose_name = "Site Settings"
        verbose_name_plural = "Site Settings"


class MainCategory(models.Model):
    title = models.CharField(max_length=200, blank=True, unique=True)
    slug = AutoSlugField(populate_from=title, editable=True, unique=True, unique_with=['created__month', 'status'])
    description = HTMLField(blank=True, null=True)
    image = models.ImageField(upload_to='category_images/', null=True, blank=True)
    featured = models.BooleanField(help_text='Select this content for main menu', default=False)
    sequence = models.PositiveIntegerField(blank=True, null=True, default=0)
    status = models.CharField(choices=STATUS_CHOICES, max_length=1, default='P')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Main Category'
        verbose_name_plural = 'Main Categories'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:main-category-detail', args=[str(self.slug)])


class NewsRoom(models.Model):
    title = models.CharField(max_length=200, blank=True, unique=True)
    description = HTMLField(blank=True, null=True)
    sequence = models.CharField(max_length=3, blank=True, null=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=1, default='P')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ['sequence']

    def __str__(self):
        return self.title


class News(models.Model):
    title = models.CharField(max_length=200)
    # slug = AutoSlugField(populate_from='title', unique=True, editable=True, allow_unicode=True)
    slug = models.CharField(unique=True, null=False, blank=True, max_length=200)
    news_room = models.ForeignKey(
        'NewsRoom',
        on_delete=models.CASCADE, blank=True, help_text='Select news room', null=True,
    )
    main_category = models.ForeignKey(
        'MainCategory',
        on_delete=models.CASCADE, blank=False, help_text='Select main category'
    )
    is_home = models.BooleanField(help_text='Select this content for home page')
    description = HTMLField()
    content_image = models.ImageField(upload_to='content_images/', blank=False)
    quote_text = models.TextField(blank=True, null=True)
    image_caption = models.CharField(max_length=200, blank=True, null=True)
    video_link = models.CharField(max_length=100, blank=True, null=True, help_text='Input YouTube Video Embed Code')
    tags = TaggableManager()
    meta_title = models.CharField(max_length=250, blank=True, null=True)
    meta_description = models.TextField(blank=True, null=True)
    meta_keywords = models.CharField(max_length=300, blank=True, null=True, help_text='Comma Separated Keyword for search engines')
    status = models.CharField(choices=STATUS_CHOICES, max_length=1, default='P')
    top_news = models.CharField(choices=HOME_NEWS_CHOICES, max_length=1, default='N')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'News'
        verbose_name_plural = 'News'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:news-detail', args=[str(self.slug)])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, allow_unicode=True)
        return super().save(*args, **kwargs)


class Page(models.Model):
    title = models.CharField(max_length=200)
    # slug = AutoSlugField(populate_from='title', unique=True, editable=True, allow_unicode=True)
    slug = models.CharField(unique=True, null=False, blank=True, max_length=200)
    description = HTMLField()
    content_image = models.ImageField(upload_to='content_images/', blank=True)
    image_caption = models.CharField(max_length=200, blank=True, null=True)
    meta_title = models.CharField(max_length=250, blank=True, null=True)
    meta_description = models.TextField(blank=True, null=True)
    meta_keywords = models.CharField(max_length=300, blank=True, null=True, help_text='Comma Separated Keyword for search engines')
    sequence = models.PositiveIntegerField(blank=True, null=True, default=0)
    status = models.CharField(choices=STATUS_CHOICES, max_length=1, default='P')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:page-detail', args=[str(self.slug)])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

core/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView, View
from django.core.paginator import Paginator
from django.db.models import Q
from .models import *
from taggit.models import Tag
# Create your views here.


def index(request):
    latest_news = News.objects.all().filter(status='P', is_home=True).order_by('-id')[0:5]
    slider_news = News.objects.all().filter(status='P', is_home=True, top_news='S').order_by('-id')[0:4]
    six_news = News.objects.all().filter(status='P', is_home=True, top_news='6').order_by('-id')[0:6]
    world_news = News.objects.all().filter(status='P', is_home=True, main_category=1).order_by('-id')[0:4]
    popular_news = News.objects.all().filter(status='P', is_home=True, main_category=2).order_by('-id')[0:9]
    editor_choice = News.objects.all().filter(status='P', is_home=True, main_category=2).order_by('-id')[0:5]
    editor_choice_1 = editor_choice[0:1]
    editor_choice_4 = editor_choice[1:5]
    context = {
        'latest_news': latest_news,
        'slider_news': slider_news,
        'six_news': six_news,
        'world_news': world_news,
        'popular_news': popular_news,
        'editor_choice_1': editor_choice_1,
        'editor_choice_4' : editor_choice_4
    }
    return render(request, 'index.html', context)


class MainCategoryDetailView(DetailView):
    model = MainCategory
    paginate_by = 1
    template_name = 'main_category_detail.html'


def category(request, slug):
    latest_news = News.objects.all().filter(status='P', is_home=True).order_by('-id')[0:6]
    cat = get_object_or_404(MainCategory, slug=slug)
    contents = News.objects.filter(main_category=cat).order_by('-id')
    paginator = Paginator(contents, 18)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'cat': cat,
        'page_obj': page_obj,
        'contents': contents,
        'latest_news': latest_news
    }
    return render(request, 'main_category_detail.html', context)


def news_details(request, slug):
    news_detail = News.objects.all().filter(slug=slug)
    current_news = get_object_or_404(News, slug=slug)
    you_may_like = News.objects.all().filter(main_category=current_news.main_category).order_by('-id').exclude(slug=slug)[0:5]
    context ={
        'news_detail': news_detail,
        'current_news': current_news,
        'you_may_like': you_may_like
    }
    return render(request, 'news_detail.html', context)


def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    contents = News.objects.filter(tags=tag)
    paginator = Paginator(contents, 18)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'tag': tag,
        'contents': contents,
        'page_obj': page_obj,
    }
    return render(request, 'tag_detail.html', context)


def search(request):
    template = 'search.html'
    query = request.GET.get('q')
    if query:
        query_list = News.objects.filter(Q(title__icontains=query) | Q(description__icontains=query)).distinct()
        query_list = query_list.filter(status='P').order_by('-created_at')
    else:
        query_list = request.GET.get('q')
    paginator = Paginator(query_list, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'query': query,
        'query_list': query_list,
        'page_obj': page_obj
    }
    return render(request, template, context)


class PageDetailView(DetailView):
    model = Page
    template_name = 'page_detail.html'

core/templates/main_category_detail.html
{% extends "index.html" %}
{% load i18n %}

    <title>{% block head_title %} {{ cat.title }} | Django News {% endblock %}</title>
    <!-- plugin css for this page -->

      {% block content %}
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="text-center">
              <h1 class="text-center mt-5">
                {{ cat.title }}
              </h1>
              <p class="text-secondary fs-15">
                {{ cat.description|safe }}
              </p>
            </div>
            <h5 class="text-muted font-weight-medium mb-3">{{ cat.title }}</h5>
          </div>
        </div>
        <div class="row">


        <div class="row">
          {% for news in contents %}
          <div class="col-sm-3  mb-5 mb-sm-2">
            <div class="position-relative image-hover">
              <img
                src="{{ news.content_image.url}}"
                class="img-fluid"
                alt="{{ news.title }}"
              />
              <span class="thumb-title">{{ news.main_category.title }}</span>
            </div>
            <h5 class="font-weight-600 mt-3">
             <a href="{% url 'core:news-detail' news.slug %}">{{ news.title }}</a>
            </h5>
          </div>
          {% endfor %}


        </div>
      </div>
      {% endblock %}
    </div>

core/templates/news_detail.html
{% extends "index.html" %}
{% load i18n %}
{% load static %}

<title>{% block head_title %} {{ current_news.title }} | Django News {% endblock %}</title>
<!-- plugin css for this page -->

{% block content %}
<div class="container">
    <div class="row">
        {% for object in news_detail %}
        <div class="col-sm-12">
            <div class="news-post-wrapper">
                <div class="news-post-wrapper-sm ">
                    <h1 class="text-center">
                        {{ object.title }}
                    </h1>
                    <div class="text-center">
                        <a href="{% url 'core:main-category-detail' object.main_category.slug %}" class="btn btn-dark font-weight-bold mb-4">{{ object.main_category.title}}</a>
                    </div>
                    <p
                            class="fs-15 d-flex justify-content-center align-items-center m-0"
                    >
                        {{ object.news_room }} | {{ object.created_at }}
                    </p>

                </div>


                <div class="row mb-5">
                    <div class="col-lg-12">
                        <img
                                src="{{ object.content_image.url }}"
                                alt="news" loading="lazy"
                                class="img-fluid mb-4"
                        />
                    </div>
                    <div class="col-lg-12">
                        <p class="text-white font-weight-medium">
                            {{ object.quote_text}}
                        </p>

                        <p>
                            {{ object.description|safe}}
                        </p>
                    </div>
                    <div>
                        <p>Share:</p>
                        <a href="https://www.facebook.com/sharer.php?u={{ request.get_host }}/news/{{ object.slug }}/"
                           onclick="javascript:window.open(this.href,
								'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"
                           title="Share on Facebook" class="facebook"><i class="fa fa-facebook-square"></i> Facebook</a>
                        <!--<a href="#" class="pinterest"><i class="fa fa-pinterest"></i> Pinterest</a>-->
                        <a href="https://www.linkedin.com/shareArticle?url={{ request.get_host }}/news/{{ object.slug }}/"
                           onclick="javascript:window.open(this.href,
								'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"
                           title="Share on LinkedIn" class="linkedin"><i class="fa fa-linkedin-square"></i>Linkedin</a>
                        <a href="https://twitter.com/intent/tweet?text={{ object.title }}&amp;url={{ request.get_host }}/news/{{ object.slug }}/"
                           onclick="javascript:window.open(this.href,
								'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"
                           class="twitter" title="Share on Twitter"><i class="fa fa-twitter-square"></i> Twitter</a>
                    </div>
                </div>

                <div class="text-center pb-5 mb-5 border-bottom">
                    {% for tag in object.tags.all %}
                    <a href="{% url 'core:tag-detail' tag.slug %}" class="btn btn-dark font-weight-bold mr-2 mb-2 mb-sm-0">{{ tag.name }}</a>
                    {% endfor %}
                </div>

                <h1 class="font-weight-600 text-center mb-5">
                    You may also like
                </h1>
                {% for news in you_may_like %}
                <div class="border-top py-5">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="position-relative image-hover">
                                <img
                                        src="{{news.content_image.url}}"
                                        alt="{{ news.image_caption }}" loading="lazy"
                                        class="img-fluid"
                                />
                                <!--                      <span class="thumb-title">NEWS</span>-->
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="position-relative image-hover">
                                <h1 class="font-weight-600">
                                    <a href="{% url 'core:news-detail' news.slug %}"> {{ news.title }}</a>
                                </h1>
                                <p class="fs-15">{{news.news_room}} | {{news.created_at}}</p>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>

</div>
</div>
{% endblock %}

core/templates/page_detail.html
{% extends "index.html" %}
{% load i18n %}
{% load static %}

<title>{% block head_title %} {{ object.title }} | Django News {% endblock %}</title>
<!-- plugin css for this page -->

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="news-post-wrapper">
                <div class="news-post-wrapper-sm ">
                    <h1 class="text-center">
                        {{ object.title }}
                    </h1>

                    <p class="fs-15 d-flex justify-content-center align-items-center m-0">
                        {{ object.created_at }}
                    </p>

                </div>


                <div class="row mb-5">
                    <div class="col-lg-12">
                        {% if object.content_image %}
                        <img
                                src="{{ object.content_image.url }}"
                                alt="news" loading="lazy"
                                class="img-fluid mb-4"
                        />
                        {% endif %}
                    </div>
                    <div class="col-lg-12">

                        <p>
                            {{ object.description|safe}}
                        </p>
                    </div>
                    <div>
                        <p>Share:</p>
                        <a href="https://www.facebook.com/sharer.php?u={{ request.get_host }}/news/{{ object.slug }}/"
                           onclick="javascript:window.open(this.href,
								'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"
                           title="Share on Facebook" class="facebook"><i class="fa fa-facebook-square"></i> Facebook</a>
                        <!--<a href="#" class="pinterest"><i class="fa fa-pinterest"></i> Pinterest</a>-->
                        <a href="https://www.linkedin.com/shareArticle?url={{ request.get_host }}/news/{{ object.slug }}/"
                           onclick="javascript:window.open(this.href,
								'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"
                           title="Share on LinkedIn" class="linkedin"><i class="fa fa-linkedin-square"></i>Linkedin</a>
                        <a href="https://twitter.com/intent/tweet?text={{ object.title }}&amp;url={{ request.get_host }}/news/{{ object.slug }}/"
                           onclick="javascript:window.open(this.href,
								'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"
                           class="twitter" title="Share on Twitter"><i class="fa fa-twitter-square"></i> Twitter</a>
                    </div>
                </div>




    </div>

</div>
</div>
{% endblock %}

core/templates/search.html
{% extends "index.html" %}
{% load i18n %}

<title>{% block head_title %} {{ request.GET.q }} | Django News {% endblock %}</title>
<!-- plugin css for this page -->

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="text-center">
                <p class="text-secondary fs-15">
                    {% if request.GET.q != '' %}
                    Search result of <strong>{{ request.GET.q }}</strong>
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
    <div class="row">


        <div class="row">
            {% for news in page_obj %}
            <div class="col-sm-3  mb-5 mb-sm-2">
                <div class="position-relative image-hover">
                    <img
                            src="{{ news.content_image.url}}"
                            class="img-fluid"
                            alt="{{ news.title }}"
                    />
                    <span class="thumb-title">{{ news.main_category.title }}</span>
                </div>
                <h5 class="font-weight-600 mt-3">
                    <a href="{% url 'core:news-detail' news.slug %}">{{ news.title }}</a>
                </h5>
                {% empty %}
                <p style="padding-left:25px;"><i class="mdi mdi-emoticon-angry-outline"></i> No result found, please
                    try with different keyword</p>
            </div>

            {% endfor %}


        </div>
    </div>
    {% endblock %}
</div>

core/templates/tag_detail.html
{% extends "index.html" %}
{% load i18n %}

    <title>{% block head_title %} {{ tag.name }} | Django News {% endblock %}</title>
    <!-- plugin css for this page -->

      {% block content %}
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="text-center">
              <h4 class="text-center mt-5">
                All news of <strong>{{ tag.name }}</strong>
              </h4>

            </div>
            <h5 class="text-muted font-weight-medium mb-3">{{ cat.title }}</h5>
          </div>
        </div>
        <div class="row">


        <div class="row">
          {% for news in contents %}
          <div class="col-sm-3  mb-5 mb-sm-2">
            <div class="position-relative image-hover">
              <img
                src="{{ news.content_image.url}}"
                class="img-fluid"
                alt="{{ news.title }}"
              />
              <span class="thumb-title">{{ news.main_category.title }}</span>
            </div>
            <h5 class="font-weight-600 mt-3">
             <a href="{% url 'core:news-detail' news.slug %}">{{ news.title }}</a>
            </h5>
          </div>
          {% endfor %}


        </div>
      </div>
      {% endblock %}
    </div>